### ISSUE TITLE
Nas能力

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/fc-alibaba#11]

**Comment by anycodes** [comment]
nas能力的表现：
1: 可以将用户指定的内容上传到Nas中
2: 可以讲nas配置到线上

具体表现：
- 当用户指定auto的时候，可以帮助用户创建一个nas，并且在之后可以使用。
- 用户配置nas之后，可以将对应文件上传到nas

**Comment by anycodes** [comment]
行为：
s nas 无行为，可以考虑输出help
s nas sync  同步所有
s nas sync -a demo 只同步指定alias

**Comment by anycodes** [comment]
```
Nas:
        UseId: userID
        GroupId: groupID # s nas sync
        MountPoints:
          - Alias: demo # 选填
            NasAddr: 3e3544a894-qjf60.cn-shanghai.nas.aliyuncs.com
            NasDir: /demo
            FcDir: /home/ssss
            LocalDir: ./ssss
          - NasAddr: 3e3544a894-qjf60.cn-shanghai.nas.aliyuncs.com
            NasDir: /demo
            FcDir: /home/aaaaaa
            LocalDir: ./ssss
```
